# PostgreSQL. Versions 9.3 and up are supported.
#
# Install the pg driver:
#   gem install pg
#
# Configure Using Gemfile
# gem 'pg'
#
default: &default
  adapter: <%= ENV['DB_ADAPTER'] ||= 'postgresql' %>
  encoding: unicode
  pool: <%= ENV['DATABASE_POOL'] || ENV['RAILS_MAX_THREADS'] || 5 %>
  host: <%= ENV['DATABASE_HOST'] %>
  port: <%= ENV['DATABASE_PORT'] %>
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  timeout: 5000

development:
  <<: *default
  database: <%= ENV.fetch('DATABASE_NAME', 'msproject_development') %>

test:
  <<: *default
  database: <%= ENV.fetch('DATABASE_NAME', 'msproject_test') %>

production:
  <<: *default
  database: <%= ENV.fetch('DATABASE_NAME', 'msproject_production') %>
