DATABASE_NAME: 'msproject_development'
DATABASE_HOST: 'localhost'
DATABASE_PORT: '5432'
DATABASE_USERNAME: 'admin'
DATABASE_PASSWORD: 'admin'
name: 'Marley Spoon'
SPACE: 'kk2bw5ojx476'
ACCESS_TOKEN: '7ac531648a1b5e1dab6c18b0979f822a5aad0fe5f1109829b8a197eb2be4b84c'
ENVIRONMENT: 'master'