DATABASE_NAME: 'DATABASE_NAME'
DATABASE_HOST: 'DATABASE_HOST'
DATABASE_PORT: 'DATABASE_PORT'
DATABASE_USERNAME: 'DATABASE_USERNAME'
DATABASE_PASSWORD: 'DATABASE_PASSWORD'
COMPANY_NAME: 'COMPANY_NAME'
SPACE: 'SPACE'
ACCESS_TOKEN: 'ACCESS_TOKEN'
ENVIRONMENT: 'ENVIRONMENT'