DATABASE_NAME: 'msproject_development'
DATABASE_HOST: 'localhost'
DATABASE_PORT: '5432'
DATABASE_USERNAME: 'admin'
DATABASE_PASSWORD: 'admin'
TEST_DATABASE_NAME: 'msproject_test'
PRODUCTION_DATABASE_NAME: 'msproject_production'